//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharterSampleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharterSampleApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number:.
        /// </summary>
        internal static string AccountNumber_ {
            get {
                return ResourceManager.GetString("AccountNumber:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already registered?.
        /// </summary>
        internal static string Alreadyregistered_ {
            get {
                return ResourceManager.GetString("Alreadyregistered?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum Sample App Version:.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.Net / MVC (6 months).
        /// </summary>
        internal static string ASP {
            get {
                return ResourceManager.GetString("ASP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available on Android and iPhone.
        /// </summary>
        internal static string AvailableOn {
            get {
                return ResourceManager.GetString("AvailableOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address:.
        /// </summary>
        internal static string BillingAddress_ {
            get {
                return ResourceManager.GetString("BillingAddress:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Details.
        /// </summary>
        internal static string BillingDetails {
            get {
                return ResourceManager.GetString("BillingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Account:.
        /// </summary>
        internal static string ConfirmYourAccount_ {
            get {
                return ResourceManager.GetString("ConfirmYourAccount:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a Xamarin Forms and WordPress developer with 5+ years of experience, I have created mobile apps, Xbox games, and business websites..
        /// </summary>
        internal static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being self-motivated, I can work unsupervised remotely for long periods of time with maximum output..
        /// </summary>
        internal static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My military experience taught me to also be a team player, able to both follow directions and take charge when the need arrives..
        /// </summary>
        internal static string Description3 {
            get {
                return ResourceManager.GetString("Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        internal static string EmailAddress_ {
            get {
                return ResourceManager.GetString("EmailAddress:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account number.
        /// </summary>
        internal static string Enteraccountnumber {
            get {
                return ResourceManager.GetString("Enteraccountnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        internal static string Enteremail {
            get {
                return ResourceManager.GetString("Enteremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string Entername {
            get {
                return ResourceManager.GetString("Entername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string Enterpassword {
            get {
                return ResourceManager.GetString("Enterpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW CHARGES.
        /// </summary>
        internal static string NEWCHARGES {
            get {
                return ResourceManager.GetString("NEWCHARGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not registered?.
        /// </summary>
        internal static string Notregistered_ {
            get {
                return ResourceManager.GetString("Notregistered?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Device Settings For This App.
        /// </summary>
        internal static string OpenDeviceSettings {
            get {
                return ResourceManager.GetString("OpenDeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        internal static string PhoneNumber_ {
            get {
                return ResourceManager.GetString("PhoneNumber:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Rest Endpoints (1 year).
        /// </summary>
        internal static string PHPRest {
            get {
                return ResourceManager.GetString("PHPRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIOUS ACCOUNT ACTIVITY.
        /// </summary>
        internal static string PREVIOUSACCOUNTACTIVITY {
            get {
                return ResourceManager.GetString("PREVIOUSACCOUNTACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Balance:.
        /// </summary>
        internal static string RemainingBalance_ {
            get {
                return ResourceManager.GetString("RemainingBalance:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Address:.
        /// </summary>
        internal static string ServiceAddress_ {
            get {
                return ResourceManager.GetString("ServiceAddress:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE FROM.
        /// </summary>
        internal static string SERVICEFROM {
            get {
                return ResourceManager.GetString("SERVICEFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In To Get Started!.
        /// </summary>
        internal static string SignInToGetStarted {
            get {
                return ResourceManager.GetString("SignInToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum Internet:.
        /// </summary>
        internal static string SpectrumInternet_ {
            get {
                return ResourceManager.GetString("SpectrumInternet:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Spectrum App!.
        /// </summary>
        internal static string TheNewSpectrumApp {
            get {
                return ResourceManager.GetString("TheNewSpectrumApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Due by.
        /// </summary>
        internal static string Total_Due_by {
            get {
                return ResourceManager.GetString("Total Due by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Due by.
        /// </summary>
        internal static string TotalDueby {
            get {
                return ResourceManager.GetString("TotalDueby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity 3D Game Developer (1 year).
        /// </summary>
        internal static string Unity3DGameDeveloper {
            get {
                return ResourceManager.GetString("Unity3DGameDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your billing statements for the last 12 months..
        /// </summary>
        internal static string View12MonthsBilling {
            get {
                return ResourceManager.GetString("View12MonthsBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordPress Developer (5 years).
        /// </summary>
        internal static string WordPressDeveloper5 {
            get {
                return ResourceManager.GetString("WordPressDeveloper5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin Forms Developer (5 years).
        /// </summary>
        internal static string XamarinFormsDeveloper5 {
            get {
                return ResourceManager.GetString("XamarinFormsDeveloper5", resourceCulture);
            }
        }
    }
}
